const mongoose = require('mongoose');

const adtAdmissionSchema = new mongoose.Schema({
  LocationName: String,
  UHid: String,
  IPNO: Number,
  AdmissionType: String,
  'Patient Name': String,
  Age: String,
  Gender: String,
  MobileNo: String,
  Father_SpouseName: String,
  Address: String,
  City: String,
  State: String,
  Country: String,
  Nationality: String,
  'Bed No': String,
  'Bed Type': String,
  'Billable Bed Type': String,
  'Ward Name': String,
  'Admission Date & Time': String,
  'Discharge Date&Time': String,
  'Bill No': String,
  'Expected Date of Discharge': String,
  Payer: String,
  PatientType: String,
  'Admitting doctor': String,
  'Admitting doctor Specialty': String,
  'Primary doctor': String,
  'Primary doctor Specialty': String,
  'Secondary doctor': String,
  'Secondary doctor Specialty': String,
  'Co specialty doctor': String,
  'Co-specialty doctor specialty': String,
  'Referral Doctor': String,
  'Source of admission': String,
  'Operator Name': String,
  BedOccupiedDateTime: String,
  IsMLC: String,
  IP_Visit: Number,
  'Admitted by': String,
  'Last Modified by': String,
  'Last Modified date/time': String,
  BillGenerateDateTime: String,
  MonthlyIncome: Number,
  PaymentType: String,
}, { collection: 'AdtAdmission' }); // ensure collection name matches MongoDB

module.exports = mongoose.model('AdtAdmission', adtAdmissionSchema);
